### ISSUE TITLE
Jeu de test : namespace du PCRS par défaut redéfini de nombreuses fois

### ISSUE THREAD

**Issue by DenisBayard** [cnigfr/PCRS#2]
L’espace de nommage par défaut du jeu de tests JeuxTestv2.gml est, à juste titre, celui du PCRS (xmlns="http://cnig.gouv.fr/pcrs"). Il est donc inutile, voire dommageable, de redéfinir cet espace de nommage pour les éléments featureMember.
Dans cet exemple cette redéfinition n’est pas utilisée :
```
	<featureMember xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:pcrs="http://cnig.gouv.fr/pcrs">
		<AffleurantGeometriquePCRS gml:id="GEOMETRIE.AffleurantEnveloppePCRS.0">
			<enveloppe xlink:href="GEOMETRIE.ENV.AffleurantEnveloppePCRS.0"/>
		</AffleurantGeometriquePCRS>
	</featureMember>

```
Correction suggérée : supprimer [xmlns:pcrs="http://cnig.gouv.fr/pcrs"]

Dans cet exemple cette redéfinition est utilisée mais ne sert à rien :
```
	<featureMember xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:pcrs="http://cnig.gouv.fr/pcrs">
		<AffleurantEnveloppePCRS gml:id="GEOMETRIE.ENV.AffleurantEnveloppePCRS.0">
			<pcrs:geometrie>
				<gml:Polygon gml:id="idelem4x61" srsName="EPSG:3948">
					<gml:exterior>
						<gml:LinearRing>
							<gml:coordinates>2051601.0101150721,7274380.1782374671 … 2051601.0101150721,7274380.1782374671</gml:coordinates>
						</gml:LinearRing>
					</gml:exterior>
				</gml:Polygon>
			</pcrs:geometrie>
		</AffleurantEnveloppePCRS>
	</featureMember>
```
Correction suggérée : supprimer [xmlns:pcrs="http://cnig.gouv.fr/pcrs"] et [pcrs:] devant « geometrie » (balise ouvrante et balise fermante).

Une recherche peut être faite pour supprimer tous les [xmlns:pcrs="http://cnig.gouv.fr/pcrs"] et tous les [pcrs:] du fichier.

**Comment by MarieLambois** [comment]
C'est corrigé.
