### ISSUE TITLE
Jeu de test : nombreux namespaces définis sans nécessité

### ISSUE THREAD

**Issue by DenisBayard** [cnigfr/PCRS#3]
Dans le jeu de tests JeuxTestv2.gml des espaces de nommages non nécessaires sont définis de nombreuses fois.

`
<featureMember xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:pcrs="http://cnig.gouv.fr/pcrs">
`

Les espaces de nommage xmlns:xs="http://www.w3.org/2001/XMLSchema" et xmlns:fn="http://www.w3.org/2005/xpath-functions" ne sont pas utilisés ; ils n’ont pas besoin d’être définis à chaque featureMember.
(idem pour xmlns:pcrs="http://cnig.gouv.fr/pcrs" mais traité un peu différemment dans l'"issue" 2.)

Correction suggérée : supprimer [xmlns:xs="http://www.w3.org/2001/XMLSchema"] et [xmlns:fn="http://www.w3.org/2005/xpath-functions"] dans tout le document.

**Comment by MarieLambois** [comment]
C'est corrigé.
