### ISSUE TITLE
Correction gabarit dans Annexe 1 : Spécifications d'orthophotoplan

### ISSUE THREAD

**Issue by gvaltat** [cnigfr/PCRS#9]
Bonjour,

Le gabarit indiqué page 3 est incorrect. 
http://cnig.gouv.fr/wp-content/uploads/2017/10/ANNEXE-1-PCRS-Specifications-dorthophotoplan.doc

Les valeurs correctes, validées par la commission des données, se trouvent slide 5 de la présentation suivante :
http://cnig.gouv.fr/wp-content/uploads/2018/12/PCRS-pr%C3%A9cision.pdf

Cordialement,
Guillaume VAltat

**Comment by MarieLambois** [comment]
Corrigé en version 1.0.1
